"""add admins

Revision ID: c719c8fee6af
Revises: f9f05ab95d65
Create Date: 2026-04-13 15:12:55.056848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c719c8fee6af"
down_revision: Union[str, Sequence[str], None] = "f9f05ab95d65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(255), nullable=True))
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "role", sa.Enum("ADMIN", "SUPERADMIN", name="userrole"), nullable=False
        ),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.VARCHAR(), nullable=False))
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "role")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
